import { invoke } from '@tauri-apps/api/core';
import { listen, UnlistenFn } from '@tauri-apps/api/event';

/**
 * Checks if the app is currently running in a Tauri desktop environment.
 */
export const isTauri = (): boolean => {
    return '__TAURI_INTERNALS__' in window;
};

/**
 * Sends a chat message to the Rust backend engine.
 * @param content The text content of the message
 * @returns A promise that resolves when the message is accepted
 */
export async function sendChatMessage(content: string): Promise<string> {
    if (!isTauri()) {
        console.warn("sendChatMessage: Not in Tauri environment. Simulating behavior.");
        return new Promise((resolve) => setTimeout(() => resolve("Simulated response"), 500));
    }
    
    return await invoke<string>('send_chat_message', { content });
}

/**
 * Listens for real-time text tokens generated by the engine.
 * @param callback Function to call when a new token arrives
 * @returns An unlisten function to clean up the event listener
 */
export async function listenToChatTokens(callback: (token: string) => void): Promise<UnlistenFn> {
    if (!isTauri()) {
        return () => {}; // Dummy unlisten for web
    }
    
    const unlisten = await listen<string>('chat_token', (event) => {
        callback(event.payload);
    });
    
    return unlisten;
}
