export interface EmojiMetadata {
  name: string;
  tags: string[];
  category: string;
  path: string;
}

export const EmojiMeta: Record<string, EmojiMetadata> = {
  "1f600": { name: "smile", tags: [":smile:"], category: "Smileys and emotions", path: "/emojis/smile_1f600.json" },
  "1f603": { name: "smilewithbigeyes", tags: [":smile-with-big-eyes:"], category: "People", path: "/emojis/smilewithbigeyes_1f603.json" },
  "1f604": { name: "grin", tags: [":grin:"], category: "Smileys and emotions", path: "/emojis/grin_1f604.json" },
  "1f601": { name: "grinning", tags: [":grinning:"], category: "Smileys and emotions", path: "/emojis/grinning_1f601.json" },
  "1f606": { name: "laughing", tags: [":laughing:"], category: "Smileys and emotions", path: "/emojis/laughing_1f606.json" },
  "1f605": { name: "grinsweat", tags: [":grin-sweat:"], category: "Smileys and emotions", path: "/emojis/grinsweat_1f605.json" },
  "1f602": { name: "joy", tags: [":joy:"], category: "Smileys and emotions", path: "/emojis/joy_1f602.json" },
  "1f923": { name: "rofl", tags: [":rofl:"], category: "Smileys and emotions", path: "/emojis/rofl_1f923.json" },
  "1f62d": { name: "loudlycrying", tags: [":loudly-crying:"], category: "Smileys and emotions", path: "/emojis/loudlycrying_1f62d.json" },
  "1f609": { name: "wink", tags: [":wink:"], category: "Smileys and emotions", path: "/emojis/wink_1f609.json" },
  "1f617": { name: "kissing", tags: [":kissing:"], category: "Smileys and emotions", path: "/emojis/kissing_1f617.json" },
  "1f619": { name: "kissingsmilingeyes", tags: [":kissing-smiling-eyes:"], category: "People", path: "/emojis/kissingsmilingeyes_1f619.json" },
  "1f61a": { name: "kissingclosedeyes", tags: [":kissing-closed-eyes:"], category: "People", path: "/emojis/kissingclosedeyes_1f61a.json" },
  "1f618": { name: "kissingheart", tags: [":kissing-heart:"], category: "People", path: "/emojis/kissingheart_1f618.json" },
  "1f970": { name: "heartface", tags: [":heart-face:", ":3-hearts:"], category: "Smileys and emotions", path: "/emojis/heartface_1f970.json" },
  "1f60d": { name: "hearteyes", tags: [":heart-eyes:"], category: "People", path: "/emojis/hearteyes_1f60d.json" },
  "1f929": { name: "starstruck", tags: [":star-struck:"], category: "Smileys and emotions", path: "/emojis/starstruck_1f929.json" },
  "1f973": { name: "partyingface", tags: [":partying-face:"], category: "Smileys and emotions", path: "/emojis/partyingface_1f973.json" },
  "1fae0": { name: "melting", tags: [":melting:"], category: "Smileys and emotions", path: "/emojis/melting_1fae0.json" },
  "1f643": { name: "upsidedownface", tags: [":upside-down-face:"], category: "Smileys and emotions", path: "/emojis/upsidedownface_1f643.json" },
  "1f642": { name: "slightlyhappy", tags: [":slightly-happy:"], category: "Smileys and emotions", path: "/emojis/slightlyhappy_1f642.json" },
  "1f972": { name: "happycry", tags: [":happy-cry:"], category: "Smileys and emotions", path: "/emojis/happycry_1f972.json" },
  "1f979": { name: "holdingbacktears", tags: [":holding-back-tears:"], category: "People", path: "/emojis/holdingbacktears_1f979.json" },
  "1f60a": { name: "blush", tags: [":blush:"], category: "Smileys and emotions", path: "/emojis/blush_1f60a.json" },
  "263a_fe0f": { name: "warmsmile", tags: [":warm-smile:"], category: "Smileys and emotions", path: "/emojis/warmsmile_263a_fe0f.json" },
  "1f60c": { name: "relieved", tags: [":relieved:"], category: "Smileys and emotions", path: "/emojis/relieved_1f60c.json" },
  "1f642_200d_2195_fe0f": { name: "headnod", tags: [":head-nod:"], category: "Smileys and emotions", path: "/emojis/headnod_1f642_200d_2195_fe0f.json" },
  "1f642_200d_2194_fe0f": { name: "headshake", tags: [":head-shake:"], category: "Smileys and emotions", path: "/emojis/headshake_1f642_200d_2194_fe0f.json" },
  "1f60f": { name: "smirk", tags: [":smirk:"], category: "Smileys and emotions", path: "/emojis/smirk_1f60f.json" },
  "1f924": { name: "drool", tags: [":drool:"], category: "Smileys and emotions", path: "/emojis/drool_1f924.json" },
  "1f60b": { name: "yum", tags: [":yum:"], category: "Smileys and emotions", path: "/emojis/yum_1f60b.json" },
  "1f61b": { name: "stuckouttongue", tags: [":stuck-out-tongue:"], category: "Smileys and emotions", path: "/emojis/stuckouttongue_1f61b.json" },
  "1f61d": { name: "squintingtongue", tags: [":squinting-tongue:"], category: "Smileys and emotions", path: "/emojis/squintingtongue_1f61d.json" },
  "1f61c": { name: "winkytongue", tags: [":winky-tongue:"], category: "Smileys and emotions", path: "/emojis/winkytongue_1f61c.json" },
  "1f92a": { name: "zanyface", tags: [":zany-face:"], category: "Smileys and emotions", path: "/emojis/zanyface_1f92a.json" },
  "1f974": { name: "woozy", tags: [":woozy:"], category: "Smileys and emotions", path: "/emojis/woozy_1f974.json" },
  "1f614": { name: "pensive", tags: [":pensive:"], category: "Smileys and emotions", path: "/emojis/pensive_1f614.json" },
  "1f97a": { name: "pleading", tags: [":pleading:"], category: "Smileys and emotions", path: "/emojis/pleading_1f97a.json" },
  "1f62c": { name: "grimacing", tags: [":grimacing:"], category: "Smileys and emotions", path: "/emojis/grimacing_1f62c.json" },
  "1f611": { name: "expressionless", tags: [":expressionless:"], category: "Smileys and emotions", path: "/emojis/expressionless_1f611.json" },
  "1f610": { name: "neutralface", tags: [":neutral-face:"], category: "Smileys and emotions", path: "/emojis/neutralface_1f610.json" },
  "1f636": { name: "mouthnone", tags: [":mouth-none:"], category: "People", path: "/emojis/mouthnone_1f636.json" },
  "1f636_200d_1f32b_fe0f": { name: "faceinclouds", tags: [":face-in-clouds:", ":lost:"], category: "Smileys and emotions", path: "/emojis/faceinclouds_1f636_200d_1f32b_fe0f.json" },
  "1fae5": { name: "dottedlineface", tags: [":dotted-line-face:", ":invisible:"], category: "Smileys and emotions", path: "/emojis/dottedlineface_1fae5.json" },
  "1f910": { name: "zipperface", tags: [":zipper-face:"], category: "Smileys and emotions", path: "/emojis/zipperface_1f910.json" },
  "1fae1": { name: "salute", tags: [":salute:"], category: "Smileys and emotions", path: "/emojis/salute_1fae1.json" },
  "1f914": { name: "thinkingface", tags: [":thinking-face:"], category: "Smileys and emotions", path: "/emojis/thinkingface_1f914.json" },
  "1f92b": { name: "shushingface", tags: [":shushing-face:"], category: "Smileys and emotions", path: "/emojis/shushingface_1f92b.json" },
  "1fae2": { name: "handovermouth", tags: [":hand-over-mouth:"], category: "People", path: "/emojis/handovermouth_1fae2.json" },
  "1f92d": { name: "smilingeyeswithhandovermouth", tags: [":smiling-eyes-with-hand-over-mouth:", ":chuckling:"], category: "People", path: "/emojis/smilingeyeswithhandovermouth_1f92d.json" },
  "1f971": { name: "yawn", tags: [":yawn:"], category: "Smileys and emotions", path: "/emojis/yawn_1f971.json" },
  "1f917": { name: "hugface", tags: [":hug-face:"], category: "Smileys and emotions", path: "/emojis/hugface_1f917.json" },
  "1fae3": { name: "peeking", tags: [":peeking:"], category: "Smileys and emotions", path: "/emojis/peeking_1fae3.json" },
  "1f631": { name: "screaming", tags: [":screaming:"], category: "Smileys and emotions", path: "/emojis/screaming_1f631.json" },
  "1f928": { name: "raisedeyebrow", tags: [":raised-eyebrow:"], category: "Smileys and emotions", path: "/emojis/raisedeyebrow_1f928.json" },
  "1f9d0": { name: "monocle", tags: [":monocle:"], category: "Smileys and emotions", path: "/emojis/monocle_1f9d0.json" },
  "1f612": { name: "unamused", tags: [":unamused:"], category: "Smileys and emotions", path: "/emojis/unamused_1f612.json" },
  "1f644": { name: "rollingeyes", tags: [":rolling-eyes:"], category: "People", path: "/emojis/rollingeyes_1f644.json" },
  "1f62e_200d_1f4a8": { name: "exhale", tags: [":exhale:"], category: "Smileys and emotions", path: "/emojis/exhale_1f62e_200d_1f4a8.json" },
  "1f624": { name: "triumph", tags: [":triumph:"], category: "Smileys and emotions", path: "/emojis/triumph_1f624.json" },
  "1f620": { name: "angry", tags: [":angry:"], category: "Smileys and emotions", path: "/emojis/angry_1f620.json" },
  "1f621": { name: "rage", tags: [":rage:"], category: "Smileys and emotions", path: "/emojis/rage_1f621.json" },
  "1f92c": { name: "cursing", tags: [":cursing:"], category: "Smileys and emotions", path: "/emojis/cursing_1f92c.json" },
  "1f61e": { name: "sad", tags: [":sad:"], category: "Smileys and emotions", path: "/emojis/sad_1f61e.json" },
  "1f613": { name: "sweat", tags: [":sweat:", ":downcast:"], category: "Smileys and emotions", path: "/emojis/sweat_1f613.json" },
  "1f61f": { name: "worried", tags: [":worried:"], category: "Smileys and emotions", path: "/emojis/worried_1f61f.json" },
  "1f625": { name: "concerned", tags: [":concerned:"], category: "Smileys and emotions", path: "/emojis/concerned_1f625.json" },
  "1f622": { name: "cry", tags: [":cry:"], category: "Smileys and emotions", path: "/emojis/cry_1f622.json" },
  "2639_fe0f": { name: "bigfrown", tags: [":big-frown:"], category: "Smileys and emotions", path: "/emojis/bigfrown_2639_fe0f.json" },
  "1f641": { name: "frown", tags: [":frown:"], category: "Smileys and emotions", path: "/emojis/frown_1f641.json" },
  "1fae4": { name: "diagonalmouth", tags: [":diagonal-mouth:"], category: "People", path: "/emojis/diagonalmouth_1fae4.json" },
  "1f615": { name: "slightlyfrowning", tags: [":slightly-frowning:"], category: "Smileys and emotions", path: "/emojis/slightlyfrowning_1f615.json" },
  "1f630": { name: "anxiouswithsweat", tags: [":anxious-with-sweat:"], category: "Smileys and emotions", path: "/emojis/anxiouswithsweat_1f630.json" },
  "1f628": { name: "scared", tags: [":scared:"], category: "Smileys and emotions", path: "/emojis/scared_1f628.json" },
  "1f627": { name: "anguished", tags: [":anguished:"], category: "Smileys and emotions", path: "/emojis/anguished_1f627.json" },
  "1f626": { name: "gasp", tags: [":gasp:"], category: "Smileys and emotions", path: "/emojis/gasp_1f626.json" },
  "1f62e": { name: "mouthopen", tags: [":mouth-open:"], category: "People", path: "/emojis/mouthopen_1f62e.json" },
  "1f62f": { name: "surprised", tags: [":surprised:", ":hushed:"], category: "Smileys and emotions", path: "/emojis/surprised_1f62f.json" },
  "1f632": { name: "astonished", tags: [":astonished:"], category: "Smileys and emotions", path: "/emojis/astonished_1f632.json" },
  "1f633": { name: "flushed", tags: [":flushed:"], category: "Smileys and emotions", path: "/emojis/flushed_1f633.json" },
  "1f92f": { name: "mindblown", tags: [":mind-blown:", ":exploding-head:"], category: "Smileys and emotions", path: "/emojis/mindblown_1f92f.json" },
  "1f616": { name: "scrunchedmouth", tags: [":scrunched-mouth:", ":confounded:", ":zigzag-mouth:"], category: "People", path: "/emojis/scrunchedmouth_1f616.json" },
  "1f623": { name: "scrunchedeyes", tags: [":scrunched-eyes:", ":persevering:"], category: "People", path: "/emojis/scrunchedeyes_1f623.json" },
  "1f629": { name: "weary", tags: [":weary:"], category: "People", path: "/emojis/weary_1f629.json" },
  "1f62b": { name: "distraught", tags: [":distraught:"], category: "Smileys and emotions", path: "/emojis/distraught_1f62b.json" },
  "1f635": { name: "xeyes", tags: [":x-eyes:"], category: "People", path: "/emojis/xeyes_1f635.json" },
  "1f635_200d_1f4ab": { name: "dizzyface", tags: [":dizzy-face:"], category: "Smileys and emotions", path: "/emojis/dizzyface_1f635_200d_1f4ab.json" },
  "1fae8": { name: "shakingface", tags: [":shaking-face:"], category: "Smileys and emotions", path: "/emojis/shakingface_1fae8.json" },
  "1f976": { name: "coldface", tags: [":cold-face:"], category: "Smileys and emotions", path: "/emojis/coldface_1f976.json" },
  "1f975": { name: "hotface", tags: [":hot-face:", ":sweat-face:"], category: "Smileys and emotions", path: "/emojis/hotface_1f975.json" },
  "1f922": { name: "sick", tags: [":sick:", ":nauseated:"], category: "Smileys and emotions", path: "/emojis/sick_1f922.json" },
  "1f92e": { name: "vomit", tags: [":vomit:"], category: "Smileys and emotions", path: "/emojis/vomit_1f92e.json" },
  "1fae9": { name: "tired", tags: [":tired:", ":bags-under-eyes:"], category: "People", path: "/emojis/tired_1fae9.json" },
  "1f634": { name: "sleep", tags: [":sleep:"], category: "Smileys and emotions", path: "/emojis/sleep_1f634.json" },
  "1f62a": { name: "sleepy", tags: [":sleepy:"], category: "Smileys and emotions", path: "/emojis/sleepy_1f62a.json" },
  "1f927": { name: "sneeze", tags: [":sneeze:"], category: "Smileys and emotions", path: "/emojis/sneeze_1f927.json" },
  "1f912": { name: "thermometerface", tags: [":thermometer-face:"], category: "Smileys and emotions", path: "/emojis/thermometerface_1f912.json" },
  "1f915": { name: "bandageface", tags: [":bandage-face:"], category: "Smileys and emotions", path: "/emojis/bandageface_1f915.json" },
  "1f637": { name: "mask", tags: [":mask:"], category: "Smileys and emotions", path: "/emojis/mask_1f637.json" },
  "1f925": { name: "liar", tags: [":liar:"], category: "Smileys and emotions", path: "/emojis/liar_1f925.json" },
  "1f607": { name: "halo", tags: [":halo:", ":innocent:"], category: "Smileys and emotions", path: "/emojis/halo_1f607.json" },
  "1f920": { name: "cowboy", tags: [":cowboy:"], category: "People", path: "/emojis/cowboy_1f920.json" },
  "1f911": { name: "moneyface", tags: [":money-face:"], category: "Smileys and emotions", path: "/emojis/moneyface_1f911.json" },
  "1f913": { name: "nerdface", tags: [":nerd-face:"], category: "Smileys and emotions", path: "/emojis/nerdface_1f913.json" },
  "1f60e": { name: "sunglassesface", tags: [":sunglasses-face:"], category: "Smileys and emotions", path: "/emojis/sunglassesface_1f60e.json" },
  "1f978": { name: "disguise", tags: [":disguise:"], category: "Smileys and emotions", path: "/emojis/disguise_1f978.json" },
  "1f921": { name: "clown", tags: [":clown:"], category: "Smileys and emotions", path: "/emojis/clown_1f921.json" },
  "1f4a9": { name: "poop", tags: [":poop:"], category: "Smileys and emotions", path: "/emojis/poop_1f4a9.json" },
  "1f608": { name: "impsmile", tags: [":imp-smile:"], category: "Smileys and emotions", path: "/emojis/impsmile_1f608.json" },
  "1f47f": { name: "impfrown", tags: [":imp-frown:"], category: "Smileys and emotions", path: "/emojis/impfrown_1f47f.json" },
  "1f47b": { name: "ghost", tags: [":ghost:"], category: "Smileys and emotions", path: "/emojis/ghost_1f47b.json" },
  "1f480": { name: "skull", tags: [":skull:"], category: "Smileys and emotions", path: "/emojis/skull_1f480.json" },
  "2603_fe0f": { name: "snowmanwithsnow", tags: [":snowman-with-snow:"], category: "People", path: "/emojis/snowmanwithsnow_2603_fe0f.json" },
  "26c4": { name: "snowman", tags: [":snowman:"], category: "People", path: "/emojis/snowman_26c4.json" },
  "1f383": { name: "jackolantern", tags: [":jack-o-lantern:"], category: "Smileys and emotions", path: "/emojis/jackolantern_1f383.json" },
  "1f916": { name: "robot", tags: [":robot:"], category: "Smileys and emotions", path: "/emojis/robot_1f916.json" },
  "1f47d": { name: "alien", tags: [":alien:"], category: "Smileys and emotions", path: "/emojis/alien_1f47d.json" },
  "1f47e": { name: "alienmonster", tags: [":alien-monster:"], category: "Smileys and emotions", path: "/emojis/alienmonster_1f47e.json" },
  "1f31e": { name: "sunwithface", tags: [":sun-with-face:"], category: "Smileys and emotions", path: "/emojis/sunwithface_1f31e.json" },
  "1f31b": { name: "moonfacefirstquarter", tags: [":moon-face-first-quarter:"], category: "Smileys and emotions", path: "/emojis/moonfacefirstquarter_1f31b.json" },
  "1f31c": { name: "moonfacelastquarter", tags: [":moon-face-last-quarter:"], category: "Smileys and emotions", path: "/emojis/moonfacelastquarter_1f31c.json" },
  "1f63a": { name: "smileycat", tags: [":smiley-cat:"], category: "Smileys and emotions", path: "/emojis/smileycat_1f63a.json" },
  "1f638": { name: "smilecat", tags: [":smile-cat:"], category: "Smileys and emotions", path: "/emojis/smilecat_1f638.json" },
  "1f639": { name: "joycat", tags: [":joy-cat:"], category: "Smileys and emotions", path: "/emojis/joycat_1f639.json" },
  "1f63b": { name: "hearteyescat", tags: [":heart-eyes-cat:"], category: "People", path: "/emojis/hearteyescat_1f63b.json" },
  "1f63c": { name: "smirkcat", tags: [":smirk-cat:"], category: "Smileys and emotions", path: "/emojis/smirkcat_1f63c.json" },
  "1f63d": { name: "kissingcat", tags: [":kissing-cat:"], category: "Smileys and emotions", path: "/emojis/kissingcat_1f63d.json" },
  "1f640": { name: "screamcat", tags: [":scream-cat:"], category: "Smileys and emotions", path: "/emojis/screamcat_1f640.json" },
  "1f63f": { name: "cryingcatface", tags: [":crying-cat-face:"], category: "Smileys and emotions", path: "/emojis/cryingcatface_1f63f.json" },
  "1f63e": { name: "poutingcat", tags: [":pouting-cat:"], category: "Smileys and emotions", path: "/emojis/poutingcat_1f63e.json" },
  "1f648": { name: "seenoevilmonkey", tags: [":see-no-evil-monkey:"], category: "Smileys and emotions", path: "/emojis/seenoevilmonkey_1f648.json" },
  "1f649": { name: "hearnoevilmonkey", tags: [":hear-no-evil-monkey:"], category: "People", path: "/emojis/hearnoevilmonkey_1f649.json" },
  "1f64a": { name: "speaknoevilmonkey", tags: [":speak-no-evil-monkey:"], category: "Smileys and emotions", path: "/emojis/speaknoevilmonkey_1f64a.json" },
  "1f31f": { name: "glowingstar", tags: [":glowing-star:"], category: "Smileys and emotions", path: "/emojis/glowingstar_1f31f.json" },
  "2728": { name: "sparkles", tags: [":sparkles:"], category: "Smileys and emotions", path: "/emojis/sparkles_2728.json" },
  "26a1": { name: "electricity", tags: [":electricity:", ":zap:", ":lightning:"], category: "Smileys and emotions", path: "/emojis/electricity_26a1.json" },
  "1f4a5": { name: "collision", tags: [":collision:"], category: "Smileys and emotions", path: "/emojis/collision_1f4a5.json" },
  "1f525": { name: "fire", tags: [":fire:", ":burn:", ":lit:"], category: "Smileys and emotions", path: "/emojis/fire_1f525.json" },
  "1f4af": { name: "100", tags: [":100:", ":one-hundred:", ":hundred:", ":points:"], category: "Smileys and emotions", path: "/emojis/100_1f4af.json" },
  "1f389": { name: "partypopper", tags: [":party-popper:"], category: "Smileys and emotions", path: "/emojis/partypopper_1f389.json" },
  "1f38a": { name: "confettiball", tags: [":confetti-ball:"], category: "Smileys and emotions", path: "/emojis/confettiball_1f38a.json" },
  "2764_fe0f": { name: "redheart", tags: [":red-heart:"], category: "People", path: "/emojis/redheart_2764_fe0f.json" },
  "1f9e1": { name: "orangeheart", tags: [":orange-heart:"], category: "People", path: "/emojis/orangeheart_1f9e1.json" },
  "1f49b": { name: "yellowheart", tags: [":yellow-heart:"], category: "People", path: "/emojis/yellowheart_1f49b.json" },
  "1f49a": { name: "greenheart", tags: [":green-heart:"], category: "People", path: "/emojis/greenheart_1f49a.json" },
  "1fa75": { name: "lightblueheart", tags: [":light-blue-heart:"], category: "People", path: "/emojis/lightblueheart_1fa75.json" },
  "1f499": { name: "blueheart", tags: [":blue-heart:"], category: "People", path: "/emojis/blueheart_1f499.json" },
  "1f49c": { name: "purpleheart", tags: [":purple-heart:"], category: "People", path: "/emojis/purpleheart_1f49c.json" },
  "1f90e": { name: "brownheart", tags: [":brown-heart:"], category: "People", path: "/emojis/brownheart_1f90e.json" },
  "1f5a4": { name: "blackheart", tags: [":black-heart:"], category: "People", path: "/emojis/blackheart_1f5a4.json" },
  "1fa76": { name: "greyheart", tags: [":grey-heart:"], category: "People", path: "/emojis/greyheart_1fa76.json" },
  "1f90d": { name: "whiteheart", tags: [":white-heart:"], category: "People", path: "/emojis/whiteheart_1f90d.json" },
  "1fa77": { name: "pinkheart", tags: [":pink-heart:"], category: "People", path: "/emojis/pinkheart_1fa77.json" },
  "1f498": { name: "cupid", tags: [":cupid:"], category: "Smileys and emotions", path: "/emojis/cupid_1f498.json" },
  "1f49d": { name: "giftheart", tags: [":gift-heart:"], category: "People", path: "/emojis/giftheart_1f49d.json" },
  "1f496": { name: "sparklingheart", tags: [":sparkling-heart:"], category: "People", path: "/emojis/sparklingheart_1f496.json" },
  "1f497": { name: "heartgrow", tags: [":heart-grow:"], category: "People", path: "/emojis/heartgrow_1f497.json" },
  "1f493": { name: "beatingheart", tags: [":beating-heart:"], category: "People", path: "/emojis/beatingheart_1f493.json" },
  "1f49e": { name: "revolvinghearts", tags: [":revolving-hearts:"], category: "People", path: "/emojis/revolvinghearts_1f49e.json" },
  "1f495": { name: "twohearts", tags: [":two-hearts:"], category: "People", path: "/emojis/twohearts_1f495.json" },
  "1f48c": { name: "loveletter", tags: [":love-letter:"], category: "Smileys and emotions", path: "/emojis/loveletter_1f48c.json" },
  "1f49f": { name: "heartbox", tags: [":heart-box:"], category: "People", path: "/emojis/heartbox_1f49f.json" },
  "2763_fe0f": { name: "heartexclamationpoint", tags: [":heart-exclamation-point:"], category: "People", path: "/emojis/heartexclamationpoint_2763_fe0f.json" },
  "2764_fe0f_200d_1fa79": { name: "bandagedheart", tags: [":bandaged-heart:"], category: "People", path: "/emojis/bandagedheart_2764_fe0f_200d_1fa79.json" },
  "1f494": { name: "brokenheart", tags: [":broken-heart:"], category: "People", path: "/emojis/brokenheart_1f494.json" },
  "2764_fe0f_200d_1f525": { name: "fireheart", tags: [":fire-heart:"], category: "People", path: "/emojis/fireheart_2764_fe0f_200d_1f525.json" },
  "1f48b": { name: "kiss", tags: [":kiss:"], category: "Smileys and emotions", path: "/emojis/kiss_1f48b.json" },
  "1f463": { name: "footprints", tags: [":footprints:"], category: "Smileys and emotions", path: "/emojis/footprints_1f463.json" },
  "1fac6": { name: "fingerprint", tags: [":fingerprint:"], category: "People", path: "/emojis/fingerprint_1fac6.json" },
  "1fac0": { name: "anatomicalheart", tags: [":anatomical-heart:"], category: "People", path: "/emojis/anatomicalheart_1fac0.json" },
  "1fa78": { name: "blood", tags: [":blood:"], category: "Smileys and emotions", path: "/emojis/blood_1fa78.json" },
  "1f9a0": { name: "microbe", tags: [":microbe:", ":virus:"], category: "Smileys and emotions", path: "/emojis/microbe_1f9a0.json" },
  "1f440": { name: "eyes", tags: [":eyes:"], category: "People", path: "/emojis/eyes_1f440.json" },
  "1f441_fe0f": { name: "eye", tags: [":eye:"], category: "Smileys and emotions", path: "/emojis/eye_1f441_fe0f.json" },
  "1fae6": { name: "bitinglip", tags: [":biting-lip:"], category: "Smileys and emotions", path: "/emojis/bitinglip_1fae6.json" },
  "1f443": { name: "nose", tags: [":nose:"], category: "People", path: "/emojis/nose_1f443.json" },
  "1f442": { name: "ear", tags: [":ear:"], category: "People", path: "/emojis/ear_1f442.json" },
  "1f9bb": { name: "hearingaid", tags: [":hearing-aid:"], category: "People", path: "/emojis/hearingaid_1f9bb.json" },
  "1f9b6": { name: "foot", tags: [":foot:"], category: "Smileys and emotions", path: "/emojis/foot_1f9b6.json" },
  "1f9b5": { name: "leg", tags: [":leg:"], category: "Smileys and emotions", path: "/emojis/leg_1f9b5.json" },
  "1f9bf": { name: "legmechanical", tags: [":leg-mechanical:"], category: "Smileys and emotions", path: "/emojis/legmechanical_1f9bf.json" },
  "1f9be": { name: "armmechanical", tags: [":arm-mechanical:"], category: "Smileys and emotions", path: "/emojis/armmechanical_1f9be.json" },
  "1f4aa": { name: "muscle", tags: [":muscle:", ":flex:", ":bicep:", ":strong:"], category: "People", path: "/emojis/muscle_1f4aa.json" },
  "1f44f": { name: "clap", tags: [":clap:"], category: "People", path: "/emojis/clap_1f44f.json" },
  "1f44d": { name: "thumbsup", tags: [":thumbs-up:", ":+1:"], category: "People", path: "/emojis/thumbsup_1f44d.json" },
  "1f44e": { name: "thumbsdown", tags: [":thumbs-down:"], category: "People", path: "/emojis/thumbsdown_1f44e.json" },
  "1faf6": { name: "hearthands", tags: [":heart-hands:"], category: "People", path: "/emojis/hearthands_1faf6.json" },
  "1f64c": { name: "raisinghands", tags: [":raising-hands:", ":hooray:"], category: "People", path: "/emojis/raisinghands_1f64c.json" },
  "1f450": { name: "openhands", tags: [":open-hands:"], category: "People", path: "/emojis/openhands_1f450.json" },
  "1f932": { name: "palmsup", tags: [":palms-up:"], category: "Smileys and emotions", path: "/emojis/palmsup_1f932.json" },
  "1f91c": { name: "fistrightwards", tags: [":fist-rightwards:"], category: "Smileys and emotions", path: "/emojis/fistrightwards_1f91c.json" },
  "1f91b": { name: "fistleftwards", tags: [":fist-leftwards:"], category: "Smileys and emotions", path: "/emojis/fistleftwards_1f91b.json" },
  "270a": { name: "raisedfist", tags: [":raised-fist:"], category: "Smileys and emotions", path: "/emojis/raisedfist_270a.json" },
  "1f44a": { name: "fist", tags: [":fist:", ":bump:"], category: "Smileys and emotions", path: "/emojis/fist_1f44a.json" },
  "1faf3": { name: "palmdown", tags: [":palm-down:", ":drop:"], category: "Smileys and emotions", path: "/emojis/palmdown_1faf3.json" },
  "1faf4": { name: "palmup", tags: [":palm-up:", ":throw:"], category: "Smileys and emotions", path: "/emojis/palmup_1faf4.json" },
  "1faf1": { name: "rightwardshand", tags: [":rightwards-hand:"], category: "People", path: "/emojis/rightwardshand_1faf1.json" },
  "1faf2": { name: "leftwardshand", tags: [":leftwards-hand:"], category: "People", path: "/emojis/leftwardshand_1faf2.json" },
  "1faf8": { name: "pushrightwards", tags: [":push-rightwards:"], category: "Smileys and emotions", path: "/emojis/pushrightwards_1faf8.json" },
  "1faf7": { name: "pushleftwards", tags: [":push-leftwards:"], category: "Smileys and emotions", path: "/emojis/pushleftwards_1faf7.json" },
  "1f44b": { name: "wave", tags: [":wave:"], category: "People", path: "/emojis/wave_1f44b.json" },
  "1f91a": { name: "backhand", tags: [":back-hand:"], category: "People", path: "/emojis/backhand_1f91a.json" },
  "1f590_fe0f": { name: "palm", tags: [":palm:"], category: "Smileys and emotions", path: "/emojis/palm_1f590_fe0f.json" },
  "270b": { name: "raisedhand", tags: [":raised-hand:"], category: "People", path: "/emojis/raisedhand_270b.json" },
  "1f596": { name: "vulcan", tags: [":vulcan:", ":prosper:", ":spock:"], category: "Smileys and emotions", path: "/emojis/vulcan_1f596.json" },
  "1f91f": { name: "loveyougesture", tags: [":love-you-gesture:"], category: "Smileys and emotions", path: "/emojis/loveyougesture_1f91f.json" },
  "1f918": { name: "metal", tags: [":metal:", ":horns:"], category: "Smileys and emotions", path: "/emojis/metal_1f918.json" },
  "270c_fe0f": { name: "victory", tags: [":victory:", ":v:", ":peace-hand:"], category: "People", path: "/emojis/victory_270c_fe0f.json" },
  "1f91e": { name: "crossedfingers", tags: [":crossed-fingers:"], category: "People", path: "/emojis/crossedfingers_1f91e.json" },
  "1faf0": { name: "handwithindexfingerandthumbcrossed", tags: [":hand-with-index-finger-and-thumb-crossed:", ":snap:", ":finger-heart:"], category: "People", path: "/emojis/handwithindexfingerandthumbcrossed_1faf0.json" },
  "1f919": { name: "callmehand", tags: [":call-me-hand:"], category: "People", path: "/emojis/callmehand_1f919.json" },
  "1f90c": { name: "pinchedfingers", tags: [":pinched-fingers:"], category: "People", path: "/emojis/pinchedfingers_1f90c.json" },
  "1f90f": { name: "pinch", tags: [":pinch:"], category: "Smileys and emotions", path: "/emojis/pinch_1f90f.json" },
  "1f44c": { name: "ok", tags: [":ok:"], category: "Smileys and emotions", path: "/emojis/ok_1f44c.json" },
  "1faf5": { name: "pointing", tags: [":pointing:"], category: "Smileys and emotions", path: "/emojis/pointing_1faf5.json" },
  "1f449": { name: "pointright", tags: [":point-right:"], category: "Smileys and emotions", path: "/emojis/pointright_1f449.json" },
  "1f448": { name: "pointleft", tags: [":point-left:"], category: "Smileys and emotions", path: "/emojis/pointleft_1f448.json" },
  "261d_fe0f": { name: "indexfinger", tags: [":index-finger:"], category: "People", path: "/emojis/indexfinger_261d_fe0f.json" },
  "1f446": { name: "pointup", tags: [":point-up:"], category: "Smileys and emotions", path: "/emojis/pointup_1f446.json" },
  "1f447": { name: "pointdown", tags: [":point-down:"], category: "Smileys and emotions", path: "/emojis/pointdown_1f447.json" },
  "1f595": { name: "middlefinger", tags: [":middle-finger:"], category: "People", path: "/emojis/middlefinger_1f595.json" },
  "270d_fe0f": { name: "writinghand", tags: [":writing-hand:"], category: "People", path: "/emojis/writinghand_270d_fe0f.json" },
  "1f933": { name: "selfie", tags: [":selfie:"], category: "Smileys and emotions", path: "/emojis/selfie_1f933.json" },
  "1f64f": { name: "foldedhands", tags: [":folded-hands:", ":please:", ":pray:", ":hope:", ":wish:", ":thank-you:", ":high-five:"], category: "People", path: "/emojis/foldedhands_1f64f.json" },
  "1f485": { name: "nailcare", tags: [":nail-care:"], category: "Smileys and emotions", path: "/emojis/nailcare_1f485.json" },
  "1f91d": { name: "handshake", tags: [":handshake:"], category: "People", path: "/emojis/handshake_1f91d.json" },
  "1f483": { name: "dancerwoman", tags: [":dancer-woman:"], category: "People", path: "/emojis/dancerwoman_1f483.json" },
  "1f490": { name: "bouquet", tags: [":bouquet:", ":flowers:"], category: "Animals and nature", path: "/emojis/bouquet_1f490.json" },
  "1f339": { name: "rose", tags: [":rose:"], category: "Animals and nature", path: "/emojis/rose_1f339.json" },
  "1f940": { name: "wiltedflower", tags: [":wilted-flower:"], category: "Animals and nature", path: "/emojis/wiltedflower_1f940.json" },
  "1f342": { name: "fallenleaf", tags: [":fallen-leaf:"], category: "Animals and nature", path: "/emojis/fallenleaf_1f342.json" },
  "1f331": { name: "plant", tags: [":plant:", ":seed:"], category: "Animals and nature", path: "/emojis/plant_1f331.json" },
  "1f343": { name: "leaves", tags: [":leaves:"], category: "Animals and nature", path: "/emojis/leaves_1f343.json" },
  "1f340": { name: "luck", tags: [":luck:", ":four-leaf-clover:"], category: "Animals and nature", path: "/emojis/luck_1f340.json" },
  "1fabe": { name: "leaflesstree", tags: [":leafless-tree:"], category: "Animals and nature", path: "/emojis/leaflesstree_1fabe.json" },
  "2744_fe0f": { name: "snowflake", tags: [":snowflake:", ":winter:", ":cold:"], category: "Animals and nature", path: "/emojis/snowflake_2744_fe0f.json" },
  "1f30b": { name: "volcano", tags: [":volcano:"], category: "Animals and nature", path: "/emojis/volcano_1f30b.json" },
  "1f305": { name: "sunrise", tags: [":sunrise:"], category: "Animals and nature", path: "/emojis/sunrise_1f305.json" },
  "1f304": { name: "sunriseovermountains", tags: [":sunrise-over-mountains:"], category: "Animals and nature", path: "/emojis/sunriseovermountains_1f304.json" },
  "1f308": { name: "rainbow", tags: [":rainbow:"], category: "Animals and nature", path: "/emojis/rainbow_1f308.json" },
  "1fae7": { name: "bubbles", tags: [":bubbles:"], category: "Animals and nature", path: "/emojis/bubbles_1fae7.json" },
  "1f30a": { name: "ocean", tags: [":ocean:"], category: "Animals and nature", path: "/emojis/ocean_1f30a.json" },
  "1f32c_fe0f": { name: "windface", tags: [":wind-face:"], category: "Animals and nature", path: "/emojis/windface_1f32c_fe0f.json" },
  "1f32a_fe0f": { name: "tornado", tags: [":tornado:"], category: "Animals and nature", path: "/emojis/tornado_1f32a_fe0f.json" },
  "1f4a7": { name: "droplet", tags: [":droplet:"], category: "Animals and nature", path: "/emojis/droplet_1f4a7.json" },
  "1f327_fe0f": { name: "raincloud", tags: [":rain-cloud:"], category: "Animals and nature", path: "/emojis/raincloud_1f327_fe0f.json" },
  "1f329_fe0f": { name: "cloudwithlightning", tags: [":cloud-with-lightning:"], category: "Animals and nature", path: "/emojis/cloudwithlightning_1f329_fe0f.json" },
  "1f30d": { name: "globeshowingeuropeafrica", tags: [":globe-showing-Europe-Africa:"], category: "Animals and nature", path: "/emojis/globeshowingeuropeafrica_1f30d.json" },
  "1f30e": { name: "globeshowingamericas", tags: [":globe-showing-Americas:"], category: "Animals and nature", path: "/emojis/globeshowingamericas_1f30e.json" },
  "1f30f": { name: "globeshowingasiaaustralia", tags: [":globe-showing-Asia-Australia:"], category: "Animals and nature", path: "/emojis/globeshowingasiaaustralia_1f30f.json" },
  "2604_fe0f": { name: "comet", tags: [":comet:"], category: "Animals and nature", path: "/emojis/comet_2604_fe0f.json" },
  "1f42e": { name: "cowface", tags: [":cow-face:"], category: "Animals and nature", path: "/emojis/cowface_1f42e.json" },
  "1f984": { name: "unicorn", tags: [":unicorn:"], category: "Animals and nature", path: "/emojis/unicorn_1f984.json" },
  "1f98e": { name: "lizard", tags: [":lizard:"], category: "Animals and nature", path: "/emojis/lizard_1f98e.json" },
  "1f409": { name: "dragon", tags: [":dragon:"], category: "Animals and nature", path: "/emojis/dragon_1f409.json" },
  "1f996": { name: "trex", tags: [":t-rex:"], category: "Animals and nature", path: "/emojis/trex_1f996.json" },
  "1f995": { name: "dinosaur", tags: [":dinosaur:"], category: "Animals and nature", path: "/emojis/dinosaur_1f995.json" },
  "1f422": { name: "turtle", tags: [":turtle:"], category: "Animals and nature", path: "/emojis/turtle_1f422.json" },
  "1f40a": { name: "crocodile", tags: [":crocodile:"], category: "Animals and nature", path: "/emojis/crocodile_1f40a.json" },
  "1f40d": { name: "snake", tags: [":snake:"], category: "Animals and nature", path: "/emojis/snake_1f40d.json" },
  "1f438": { name: "frog", tags: [":frog:"], category: "Animals and nature", path: "/emojis/frog_1f438.json" },
  "1f407": { name: "rabbit", tags: [":rabbit:"], category: "Animals and nature", path: "/emojis/rabbit_1f407.json" },
  "1f400": { name: "rat", tags: [":rat:"], category: "Animals and nature", path: "/emojis/rat_1f400.json" },
  "1f429": { name: "poodle", tags: [":poodle:"], category: "Animals and nature", path: "/emojis/poodle_1f429.json" },
  "1f415": { name: "dog", tags: [":dog:"], category: "Animals and nature", path: "/emojis/dog_1f415.json" },
  "1f9ae": { name: "guidedog", tags: [":guide-dog:"], category: "Animals and nature", path: "/emojis/guidedog_1f9ae.json" },
  "1f415_200d_1f9ba": { name: "servicedog", tags: [":service-dog:"], category: "Animals and nature", path: "/emojis/servicedog_1f415_200d_1f9ba.json" },
  "1f416": { name: "pig", tags: [":pig:"], category: "Animals and nature", path: "/emojis/pig_1f416.json" },
  "1f40e": { name: "racehorse", tags: [":racehorse:"], category: "Animals and nature", path: "/emojis/racehorse_1f40e.json" },
  "1facf": { name: "donkey", tags: [":donkey:"], category: "Animals and nature", path: "/emojis/donkey_1facf.json" },
  "1f402": { name: "ox", tags: [":ox:"], category: "Animals and nature", path: "/emojis/ox_1f402.json" },
  "1f410": { name: "goat", tags: [":goat:"], category: "Animals and nature", path: "/emojis/goat_1f410.json" },
  "1f998": { name: "kangaroo", tags: [":kangaroo:"], category: "Animals and nature", path: "/emojis/kangaroo_1f998.json" },
  "1f405": { name: "tiger", tags: [":tiger:"], category: "Animals and nature", path: "/emojis/tiger_1f405.json" },
  "1f412": { name: "monkey", tags: [":monkey:"], category: "Animals and nature", path: "/emojis/monkey_1f412.json" },
  "1f98d": { name: "gorilla", tags: [":gorilla:"], category: "Animals and nature", path: "/emojis/gorilla_1f98d.json" },
  "1f9a7": { name: "orangutan", tags: [":orangutan:"], category: "Animals and nature", path: "/emojis/orangutan_1f9a7.json" },
  "1f43f_fe0f": { name: "chipmunk", tags: [":chipmunk:"], category: "Animals and nature", path: "/emojis/chipmunk_1f43f_fe0f.json" },
  "1f9a6": { name: "otter", tags: [":otter:"], category: "Animals and nature", path: "/emojis/otter_1f9a6.json" },
  "1f987": { name: "bat", tags: [":bat:"], category: "Animals and nature", path: "/emojis/bat_1f987.json" },
  "1f426": { name: "bird", tags: [":bird:"], category: "Animals and nature", path: "/emojis/bird_1f426.json" },
  "1f426_200d_2b1b": { name: "blackbird", tags: [":black-bird:"], category: "Animals and nature", path: "/emojis/blackbird_1f426_200d_2b1b.json" },
  "1f413": { name: "rooster", tags: [":rooster:"], category: "Animals and nature", path: "/emojis/rooster_1f413.json" },
  "1f423": { name: "hatchingchick", tags: [":hatching-chick:"], category: "Animals and nature", path: "/emojis/hatchingchick_1f423.json" },
  "1f424": { name: "babychick", tags: [":baby-chick:"], category: "Animals and nature", path: "/emojis/babychick_1f424.json" },
  "1f425": { name: "hatchedchick", tags: [":hatched-chick:"], category: "Animals and nature", path: "/emojis/hatchedchick_1f425.json" },
  "1f985": { name: "eagle", tags: [":eagle:"], category: "Animals and nature", path: "/emojis/eagle_1f985.json" },
  "1f989": { name: "owl", tags: [":owl:"], category: "Animals and nature", path: "/emojis/owl_1f989.json" },
  "1f54a_fe0f": { name: "peace", tags: [":peace:", ":dove:"], category: "Animals and nature", path: "/emojis/peace_1f54a_fe0f.json" },
  "1fabf": { name: "goose", tags: [":goose:"], category: "Animals and nature", path: "/emojis/goose_1fabf.json" },
  "1f99a": { name: "peacock", tags: [":peacock:"], category: "Animals and nature", path: "/emojis/peacock_1f99a.json" },
  "1f426_200d_1f525": { name: "phoenix", tags: [":phoenix:"], category: "Animals and nature", path: "/emojis/phoenix_1f426_200d_1f525.json" },
  "1f9ad": { name: "seal", tags: [":seal:"], category: "Animals and nature", path: "/emojis/seal_1f9ad.json" },
  "1f988": { name: "shark", tags: [":shark:"], category: "Animals and nature", path: "/emojis/shark_1f988.json" },
  "1f42c": { name: "dolphin", tags: [":dolphin:"], category: "Animals and nature", path: "/emojis/dolphin_1f42c.json" },
  "1f433": { name: "whale", tags: [":whale:"], category: "Animals and nature", path: "/emojis/whale_1f433.json" },
  "1f41f": { name: "fish", tags: [":fish:"], category: "Animals and nature", path: "/emojis/fish_1f41f.json" },
  "1f421": { name: "blowfish", tags: [":blowfish:"], category: "Animals and nature", path: "/emojis/blowfish_1f421.json" },
  "1f99e": { name: "lobster", tags: [":lobster:"], category: "Animals and nature", path: "/emojis/lobster_1f99e.json" },
  "1f980": { name: "crab", tags: [":crab:"], category: "Animals and nature", path: "/emojis/crab_1f980.json" },
  "1f419": { name: "octopus", tags: [":octopus:"], category: "Animals and nature", path: "/emojis/octopus_1f419.json" },
  "1fabc": { name: "jellyfish", tags: [":jellyfish:"], category: "Animals and nature", path: "/emojis/jellyfish_1fabc.json" },
  "1f982": { name: "scorpion", tags: [":scorpion:"], category: "Animals and nature", path: "/emojis/scorpion_1f982.json" },
  "1f577_fe0f": { name: "spider", tags: [":spider:"], category: "Animals and nature", path: "/emojis/spider_1f577_fe0f.json" },
  "1f40c": { name: "snail", tags: [":snail:"], category: "Animals and nature", path: "/emojis/snail_1f40c.json" },
  "1f41c": { name: "ant", tags: [":ant:"], category: "Animals and nature", path: "/emojis/ant_1f41c.json" },
  "1f99f": { name: "mosquito", tags: [":mosquito:"], category: "Animals and nature", path: "/emojis/mosquito_1f99f.json" },
  "1fab3": { name: "cockroach", tags: [":cockroach:"], category: "Animals and nature", path: "/emojis/cockroach_1fab3.json" },
  "1fab0": { name: "fly", tags: [":fly:"], category: "Animals and nature", path: "/emojis/fly_1fab0.json" },
  "1f41d": { name: "bee", tags: [":bee:"], category: "Animals and nature", path: "/emojis/bee_1f41d.json" },
  "1f41e": { name: "ladybug", tags: [":lady-bug:"], category: "Animals and nature", path: "/emojis/ladybug_1f41e.json" },
  "1f98b": { name: "butterfly", tags: [":butterfly:"], category: "Animals and nature", path: "/emojis/butterfly_1f98b.json" },
  "1f41b": { name: "bug", tags: [":bug:"], category: "Animals and nature", path: "/emojis/bug_1f41b.json" },
  "1fab1": { name: "worm", tags: [":worm:"], category: "Animals and nature", path: "/emojis/worm_1fab1.json" },
  "1f43e": { name: "paw_prints", tags: [":paw prints:"], category: "Animals and nature", path: "/emojis/paw_prints_1f43e.json" },
  "1f345": { name: "tomato", tags: [":tomato:"], category: "Food and drink", path: "/emojis/tomato_1f345.json" },
  "1fadc": { name: "rootvegetable", tags: [":root-vegetable:", ":beet:", ":turnip:"], category: "Food and drink", path: "/emojis/rootvegetable_1fadc.json" },
  "1f373": { name: "cooking", tags: [":cooking:"], category: "Food and drink", path: "/emojis/cooking_1f373.json" },
  "1f32f": { name: "burrito", tags: [":burrito:"], category: "Food and drink", path: "/emojis/burrito_1f32f.json" },
  "1f35d": { name: "spaghetti", tags: [":spaghetti:"], category: "Food and drink", path: "/emojis/spaghetti_1f35d.json" },
  "1f35c": { name: "steamingbowl", tags: [":steaming-bowl:"], category: "Food and drink", path: "/emojis/steamingbowl_1f35c.json" },
  "1f37f": { name: "popcorn", tags: [":popcorn:"], category: "Food and drink", path: "/emojis/popcorn_1f37f.json" },
  "2615": { name: "hotbeverage", tags: [":hot-beverage:"], category: "Food and drink", path: "/emojis/hotbeverage_2615.json" },
  "1f37b": { name: "clinkingbeermugs", tags: [":clinking-beer-mugs:"], category: "Food and drink", path: "/emojis/clinkingbeermugs_1f37b.json" },
  "1f942": { name: "clinkingglasses", tags: [":clinking-glasses:"], category: "Food and drink", path: "/emojis/clinkingglasses_1f942.json" },
  "1f37e": { name: "bottlewithpoppingcork", tags: [":bottle-with-popping-cork:"], category: "Food and drink", path: "/emojis/bottlewithpoppingcork_1f37e.json" },
  "1f377": { name: "wineglass", tags: [":wine-glass:"], category: "Food and drink", path: "/emojis/wineglass_1f377.json" },
  "1fad7": { name: "pour", tags: [":pour:"], category: "Food and drink", path: "/emojis/pour_1fad7.json" },
  "1f379": { name: "tropicaldrink", tags: [":tropical-drink:"], category: "Food and drink", path: "/emojis/tropicaldrink_1f379.json" },
  "1f6a7": { name: "construction", tags: [":construction:"], category: "Travel and places", path: "/emojis/construction_1f6a7.json" },
  "1f6a8": { name: "policecarlight", tags: [":police-car-light:"], category: "Travel and places", path: "/emojis/policecarlight_1f6a8.json" },
  "1f6b2": { name: "bicycle", tags: [":bicycle:"], category: "Travel and places", path: "/emojis/bicycle_1f6b2.json" },
  "1f697": { name: "automobile", tags: [":automobile:"], category: "Travel and places", path: "/emojis/automobile_1f697.json" },
  "1f3ce_fe0f": { name: "racingcar", tags: [":racing-car:"], category: "Travel and places", path: "/emojis/racingcar_1f3ce_fe0f.json" },
  "1f695": { name: "taxi", tags: [":taxi:"], category: "Travel and places", path: "/emojis/taxi_1f695.json" },
  "1f68c": { name: "bus", tags: [":bus:"], category: "Travel and places", path: "/emojis/bus_1f68c.json" },
  "26f5": { name: "sailboat", tags: [":sailboat:"], category: "Travel and places", path: "/emojis/sailboat_26f5.json" },
  "1f6f6": { name: "canoe", tags: [":canoe:"], category: "Travel and places", path: "/emojis/canoe_1f6f6.json" },
  "1f6f8": { name: "flyingsaucer", tags: [":flying-saucer:"], category: "Travel and places", path: "/emojis/flyingsaucer_1f6f8.json" },
  "1f680": { name: "rocket", tags: [":rocket:"], category: "Travel and places", path: "/emojis/rocket_1f680.json" },
  "1f6eb": { name: "airplanedeparture", tags: [":airplane-departure:"], category: "Travel and places", path: "/emojis/airplanedeparture_1f6eb.json" },
  "1f6ec": { name: "airplanearrival", tags: [":airplane-arrival:"], category: "Travel and places", path: "/emojis/airplanearrival_1f6ec.json" },
  "1f3a2": { name: "rollercoaster", tags: [":roller-coaster:"], category: "Travel and places", path: "/emojis/rollercoaster_1f3a2.json" },
  "1f3a1": { name: "ferriswheel", tags: [":ferris-wheel:"], category: "Travel and places", path: "/emojis/ferriswheel_1f3a1.json" },
  "1f3d5_fe0f": { name: "camping", tags: [":camping:"], category: "Travel and places", path: "/emojis/camping_1f3d5_fe0f.json" },
  "1f388": { name: "balloon", tags: [":balloon:"], category: "Activities and events", path: "/emojis/balloon_1f388.json" },
  "1f382": { name: "birthdaycake", tags: [":birthday-cake:"], category: "Activities and events", path: "/emojis/birthdaycake_1f382.json" },
  "1f381": { name: "wrappedgift", tags: [":wrapped-gift:"], category: "Activities and events", path: "/emojis/wrappedgift_1f381.json" },
  "1f386": { name: "fireworks", tags: [":fireworks:"], category: "Activities and events", path: "/emojis/fireworks_1f386.json" },
  "1fa85": { name: "piata", tags: [":piñata:"], category: "Activities and events", path: "/emojis/piata_1fa85.json" },
  "1faa9": { name: "mirrorball", tags: [":mirror-ball:", ":disco-ball:"], category: "Activities and events", path: "/emojis/mirrorball_1faa9.json" },
  "1f947": { name: "goldmedal", tags: [":gold-medal:", ":1st-place-medal:"], category: "Activities and events", path: "/emojis/goldmedal_1f947.json" },
  "1f948": { name: "silvermedal", tags: [":silver-medal:", ":2nd-place-medal:"], category: "Activities and events", path: "/emojis/silvermedal_1f948.json" },
  "1f949": { name: "bronzemedal", tags: [":bronze-medal:", ":3rd-place-medal:"], category: "Activities and events", path: "/emojis/bronzemedal_1f949.json" },
  "1f3c6": { name: "trophy", tags: [":trophy:"], category: "Activities and events", path: "/emojis/trophy_1f3c6.json" },
  "26bd": { name: "soccerball", tags: [":soccer-ball:"], category: "Activities and events", path: "/emojis/soccerball_26bd.json" },
  "26be": { name: "baseball", tags: [":baseball:"], category: "Activities and events", path: "/emojis/baseball_26be.json" },
  "1f94e": { name: "softball", tags: [":softball:"], category: "Activities and events", path: "/emojis/softball_1f94e.json" },
  "1f3be": { name: "tennis", tags: [":tennis:"], category: "Activities and events", path: "/emojis/tennis_1f3be.json" },
  "1f3f8": { name: "badminton", tags: [":badminton:"], category: "Activities and events", path: "/emojis/badminton_1f3f8.json" },
  "1f94d": { name: "lacrosse", tags: [":lacrosse:"], category: "Activities and events", path: "/emojis/lacrosse_1f94d.json" },
  "1f3cf": { name: "cricketgame", tags: [":cricket-game:"], category: "Activities and events", path: "/emojis/cricketgame_1f3cf.json" },
  "1f3d1": { name: "fieldhockey", tags: [":field-hockey:"], category: "Activities and events", path: "/emojis/fieldhockey_1f3d1.json" },
  "1f3d2": { name: "icehockey", tags: [":ice-hockey:"], category: "Activities and events", path: "/emojis/icehockey_1f3d2.json" },
  "26f8_fe0f": { name: "iceskate", tags: [":ice-skate:"], category: "Activities and events", path: "/emojis/iceskate_26f8_fe0f.json" },
  "1f6fc": { name: "rollerskates", tags: [":roller-skates:"], category: "Activities and events", path: "/emojis/rollerskates_1f6fc.json" },
  "1fa70": { name: "balletshoes", tags: [":ballet-shoes:"], category: "Activities and events", path: "/emojis/balletshoes_1fa70.json" },
  "1f6f9": { name: "skateboard", tags: [":skateboard:"], category: "Activities and events", path: "/emojis/skateboard_1f6f9.json" },
  "26f3": { name: "flaginhole", tags: [":flag-in-hole:"], category: "Activities and events", path: "/emojis/flaginhole_26f3.json" },
  "1f3af": { name: "directhit", tags: [":direct-hit:", ":target:"], category: "Activities and events", path: "/emojis/directhit_1f3af.json" },
  "1f94f": { name: "flyingdisc", tags: [":flying-disc:"], category: "Activities and events", path: "/emojis/flyingdisc_1f94f.json" },
  "1fa83": { name: "boomerang", tags: [":boomerang:"], category: "Activities and events", path: "/emojis/boomerang_1fa83.json" },
  "1fa81": { name: "kite", tags: [":kite:"], category: "Activities and events", path: "/emojis/kite_1fa81.json" },
  "1f3a3": { name: "fishingpole", tags: [":fishing-pole:"], category: "Activities and events", path: "/emojis/fishingpole_1f3a3.json" },
  "1f94b": { name: "martialartsuniform", tags: [":martial-arts-uniform:"], category: "Activities and events", path: "/emojis/martialartsuniform_1f94b.json" },
  "1f3b1": { name: "8ball", tags: [":8-ball:"], category: "Activities and events", path: "/emojis/8ball_1f3b1.json" },
  "1f3d3": { name: "pingpong", tags: [":ping-pong:"], category: "Activities and events", path: "/emojis/pingpong_1f3d3.json" },
  "1f3b3": { name: "bowling", tags: [":bowling:"], category: "Activities and events", path: "/emojis/bowling_1f3b3.json" },
  "1f3b2": { name: "die", tags: [":die:"], category: "Activities and events", path: "/emojis/die_1f3b2.json" },
  "1f3b0": { name: "slotmachine", tags: [":slot-machine:"], category: "Activities and events", path: "/emojis/slotmachine_1f3b0.json" },
  "1fa84": { name: "wand", tags: [":wand:"], category: "Activities and events", path: "/emojis/wand_1fa84.json" },
  "1f4f8": { name: "cameraflash", tags: [":camera-flash:"], category: "Activities and events", path: "/emojis/cameraflash_1f4f8.json" },
  "1fadf": { name: "splatter", tags: [":splatter:"], category: "Activities and events", path: "/emojis/splatter_1fadf.json" },
  "1f3b7": { name: "saxophone", tags: [":saxophone:"], category: "Activities and events", path: "/emojis/saxophone_1f3b7.json" },
  "1f3ba": { name: "trumpet", tags: [":trumpet:"], category: "Activities and events", path: "/emojis/trumpet_1f3ba.json" },
  "1f3bb": { name: "violin", tags: [":violin:"], category: "Activities and events", path: "/emojis/violin_1f3bb.json" },
  "1fa89": { name: "harp", tags: [":harp:"], category: "Activities and events", path: "/emojis/harp_1fa89.json" },
  "1f941": { name: "drum", tags: [":drum:"], category: "Activities and events", path: "/emojis/drum_1f941.json" },
  "1fa87": { name: "maracas", tags: [":maracas:"], category: "Activities and events", path: "/emojis/maracas_1fa87.json" },
  "1f3ac": { name: "clapper", tags: [":clapper:"], category: "Activities and events", path: "/emojis/clapper_1f3ac.json" },
  "1f50b": { name: "batteryfull", tags: [":battery-full:"], category: "Objects", path: "/emojis/batteryfull_1f50b.json" },
  "1faab": { name: "batterylow", tags: [":battery-low:"], category: "Objects", path: "/emojis/batterylow_1faab.json" },
  "1fa99": { name: "coin", tags: [":coin:"], category: "Objects", path: "/emojis/coin_1fa99.json" },
  "1f4b8": { name: "moneywithwings", tags: [":money-with-wings:"], category: "Objects", path: "/emojis/moneywithwings_1f4b8.json" },
  "1f48e": { name: "gemstone", tags: [":gem-stone:"], category: "Objects", path: "/emojis/gemstone_1f48e.json" },
  "2696_fe0f": { name: "balancescale", tags: [":balance-scale:"], category: "Objects", path: "/emojis/balancescale_2696_fe0f.json" },
  "1f4a1": { name: "lightbulb", tags: [":light-bulb:"], category: "Objects", path: "/emojis/lightbulb_1f4a1.json" },
  "1f393": { name: "graduationcap", tags: [":graduation-cap:"], category: "Objects", path: "/emojis/graduationcap_1f393.json" },
  "1f48d": { name: "ring", tags: [":ring:"], category: "Objects", path: "/emojis/ring_1f48d.json" },
  "1faad": { name: "fan", tags: [":fan:"], category: "Objects", path: "/emojis/fan_1faad.json" },
  "2602_fe0f": { name: "umbrella", tags: [":umbrella:"], category: "Objects", path: "/emojis/umbrella_2602_fe0f.json" },
  "1fa8f": { name: "shovel", tags: [":shovel:", ":dig:"], category: "Objects", path: "/emojis/shovel_1fa8f.json" },
  "2699_fe0f": { name: "gear", tags: [":gear:"], category: "Objects", path: "/emojis/gear_2699_fe0f.json" },
  "26d3_fe0f_200d_1f4a5": { name: "brokenchain", tags: [":broken-chain:"], category: "Objects", path: "/emojis/brokenchain_26d3_fe0f_200d_1f4a5.json" },
  "270f_fe0f": { name: "pencil", tags: [":pencil:"], category: "Objects", path: "/emojis/pencil_270f_fe0f.json" },
  "23f0": { name: "alarmclock", tags: [":alarm-clock:"], category: "Objects", path: "/emojis/alarmclock_23f0.json" },
  "1f6ce_fe0f": { name: "bellhopbell", tags: [":bellhop-bell:"], category: "Objects", path: "/emojis/bellhopbell_1f6ce_fe0f.json" },
  "1f514": { name: "bell", tags: [":bell:"], category: "Objects", path: "/emojis/bell_1f514.json" },
  "1f52e": { name: "crystalball", tags: [":crystal-ball:"], category: "Objects", path: "/emojis/crystalball_1f52e.json" },
  "1f4a3": { name: "bomb", tags: [":bomb:"], category: "Objects", path: "/emojis/bomb_1f4a3.json" },
  "1faa4": { name: "mousetrap", tags: [":mouse-trap:"], category: "Objects", path: "/emojis/mousetrap_1faa4.json" },
  "1f512": { name: "locked", tags: [":locked:"], category: "Objects", path: "/emojis/locked_1f512.json" },
  "2648": { name: "aries", tags: [":Aries:"], category: "Symbols", path: "/emojis/aries_2648.json" },
  "2649": { name: "taurus", tags: [":Taurus:"], category: "Symbols", path: "/emojis/taurus_2649.json" },
  "264a": { name: "gemini", tags: [":Gemini:"], category: "Symbols", path: "/emojis/gemini_264a.json" },
  "264b": { name: "cancer", tags: [":Cancer:"], category: "Symbols", path: "/emojis/cancer_264b.json" },
  "264c": { name: "leo", tags: [":Leo:"], category: "Symbols", path: "/emojis/leo_264c.json" },
  "264d": { name: "virgo", tags: [":Virgo:"], category: "Symbols", path: "/emojis/virgo_264d.json" },
  "264e": { name: "libra", tags: [":Libra:"], category: "Symbols", path: "/emojis/libra_264e.json" },
  "264f": { name: "scorpio", tags: [":Scorpio:"], category: "Symbols", path: "/emojis/scorpio_264f.json" },
  "2650": { name: "sagittarius", tags: [":Sagittarius:"], category: "Symbols", path: "/emojis/sagittarius_2650.json" },
  "2651": { name: "capricorn", tags: [":Capricorn:"], category: "Symbols", path: "/emojis/capricorn_2651.json" },
  "2652": { name: "aquarius", tags: [":Aquarius:"], category: "Symbols", path: "/emojis/aquarius_2652.json" },
  "2653": { name: "pisces", tags: [":Pisces:"], category: "Symbols", path: "/emojis/pisces_2653.json" },
  "26ce": { name: "ophiuchus", tags: [":Ophiuchus:"], category: "Symbols", path: "/emojis/ophiuchus_26ce.json" },
  "2757": { name: "exclamation", tags: [":exclamation:", ":exclamation-mark:"], category: "Symbols", path: "/emojis/exclamation_2757.json" },
  "2753": { name: "question", tags: [":question:", ":question-mark:", ":?:"], category: "Symbols", path: "/emojis/question_2753.json" },
  "2049_fe0f": { name: "exclamationquestionmark", tags: [":exclamation-question-mark:", ":!?:"], category: "Symbols", path: "/emojis/exclamationquestionmark_2049_fe0f.json" },
  "203c_fe0f": { name: "exclamationdouble", tags: [":exclamation-double:", ":!!:"], category: "Symbols", path: "/emojis/exclamationdouble_203c_fe0f.json" },
  "274c": { name: "crossmark", tags: [":cross-mark:", ":x:"], category: "Symbols", path: "/emojis/crossmark_274c.json" },
  "1f198": { name: "sos", tags: [":sos:"], category: "Symbols", path: "/emojis/sos_1f198.json" },
  "1f4f4": { name: "phoneoff", tags: [":phone-off:"], category: "Symbols", path: "/emojis/phoneoff_1f4f4.json" },
  "2622_fe0f": { name: "radioactive", tags: [":radioactive:"], category: "Symbols", path: "/emojis/radioactive_2622_fe0f.json" },
  "2623_fe0f": { name: "biohazard", tags: [":biohazard:"], category: "Symbols", path: "/emojis/biohazard_2623_fe0f.json" },
  "26a0_fe0f": { name: "warning", tags: [":warning:"], category: "Symbols", path: "/emojis/warning_26a0_fe0f.json" },
  "2705": { name: "checkmark", tags: [":check-mark:", ":check-mark-green:"], category: "Symbols", path: "/emojis/checkmark_2705.json" },
  "1f195": { name: "new", tags: [":new:"], category: "Symbols", path: "/emojis/new_1f195.json" },
  "1f193": { name: "free", tags: [":free:"], category: "Symbols", path: "/emojis/free_1f193.json" },
  "1f199": { name: "up", tags: [":up!:"], category: "Symbols", path: "/emojis/up_1f199.json" },
  "1f192": { name: "cool", tags: [":cool:"], category: "Symbols", path: "/emojis/cool_1f192.json" },
  "1f6ae": { name: "litter", tags: [":litter:"], category: "Symbols", path: "/emojis/litter_1f6ae.json" },
  "262e_fe0f": { name: "peacesymbol", tags: [":peace-symbol:"], category: "Symbols", path: "/emojis/peacesymbol_262e_fe0f.json" },
  "262f_fe0f": { name: "yinyang", tags: [":yin-yang:"], category: "Symbols", path: "/emojis/yinyang_262f_fe0f.json" },
  "267e_fe0f": { name: "infinity", tags: [":infinity:"], category: "Symbols", path: "/emojis/infinity_267e_fe0f.json" },
  "1f3b6": { name: "musicalnotes", tags: [":musical-notes:"], category: "Symbols", path: "/emojis/musicalnotes_1f3b6.json" },
  "2795": { name: "plussign", tags: [":plus-sign:", ":+:"], category: "Symbols", path: "/emojis/plussign_2795.json" },
  "1f3c1": { name: "chequeredflag", tags: [":chequered-flag:"], category: "Flags", path: "/emojis/chequeredflag_1f3c1.json" },
  "1f6a9": { name: "triangularflag", tags: [":triangular-flag:"], category: "Flags", path: "/emojis/triangularflag_1f6a9.json" },
  "1f3f4": { name: "blackflag", tags: [":black-flag:"], category: "Flags", path: "/emojis/blackflag_1f3f4.json" },
  "1f3f3_fe0f": { name: "whiteflag", tags: [":white-flag:"], category: "Flags", path: "/emojis/whiteflag_1f3f3_fe0f.json" },
};
